spring:
  datasource:
    url: jdbc:mysql://localhost:3306/CellphoneCompany
    username: root
    password: mysql

  jpa:
    show-sql: true

  h2:
    console:
      enabled: true
      path: /h2-console